title: "Nippon.fr"
description: "Stories about Japan and France."
url: "https://nippon.fr"
author:
  name: "Nippon.fr"
  email: "aki@akispace.net"
  url: "https://nippon.fr"

baseurl: /

defaults:
  - scope:
      path: "img"
    values:
      image: true

# Custom variables
version: "1.0.1"

# Options
permalink: pretty
custom_header: true
custom_nav_footer: false
reverse: false
