title: "Nippon.fr"
description: "Stories about Japan."
url: "https://phocean.github.io/nippon.fr"
author:
  name: "Nippon.fr"
  email: "aki@akispace.net"
  url: "https://phocean.github.io/nippon.fr"

baseurl: /

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

include: ['_pages']

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
