title: "Nippon.fr"
description: "Stories about Japan and France."
url: "https://nippon.fr"
author:
  name: "Nippon.fr"
  email: "aki@akispace.net"
  url: "https://nippon.fr"

baseurl: /

defaults:
  - scope:
      path: "img"
    values:
      image: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
