title: "AkiSpace - English teaching"
description: "English teaching in Paris, France."
url: "https://akispace.net"
author:
  name: "Akispace.net"
  email: "aki@akispace.net"
  url: "https://akispace.net"

baseurl: /

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

include: ['_pages']

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
